-- /make_sgnet_disk.lua
-- SGNet unified installer disk builder for CC: Tweaked
-- Run this on a CC:Tweaked computer with a disk drive and writable floppy disk.

local VERSION = "sgnet-stable-ae2-rollback-v4"

local INSTALLER_LUA = [=====[
-- /disk/install.lua
-- SGNet unified installer

local function clear()
  term.clear()
  term.setCursorPos(1, 1)
end

local function trim(value)
  value = tostring(value or "")
  return string.match(value, "^%s*(.-)%s*$") or value
end

local function askString(prompt, default)
  while true do
    if default and default ~= "" then
      write(prompt .. " [" .. tostring(default) .. "]: ")
    else
      write(prompt .. ": ")
    end

    local answer = trim(read())
    if answer == "" and default then answer = default end

    if answer ~= "" then return answer end
    print("This value cannot be empty.")
  end
end

local function askYesNo(prompt, default)
  while true do
    local suffix = default and " [Y/n]: " or " [y/N]: "
    write(prompt .. suffix)

    local answer = string.lower(trim(read()))
    if answer == "" then
      return default
    elseif answer == "y" or answer == "yes" then
      return true
    elseif answer == "n" or answer == "no" then
      return false
    end

    print("Please answer y or n.")
  end
end

local function askNumber(prompt, default, allowBlank)
  while true do
    if default ~= nil then
      write(prompt .. " [" .. tostring(default) .. "]: ")
    elseif allowBlank then
      write(prompt .. " [blank for none]: ")
    else
      write(prompt .. ": ")
    end

    local answer = trim(read())
    if answer == "" then
      if allowBlank then return nil end
      if default ~= nil then return default end
    end

    local number = tonumber(answer)
    if number then return number end

    print("Please enter a number.")
  end
end

local function askRole()
  while true do
    print("")
    print("Choose SGNet role:")
    print("1) controller")
    print("2) gateway")
    write("> ")

    local answer = string.lower(trim(read()))
    if answer == "1" or answer == "controller" then return "controller" end
    if answer == "2" or answer == "gateway" then return "gateway" end

    print("Invalid choice.")
  end
end

local function writeFile(path, content)
  local dir = fs.getDir(path)
  if dir and dir ~= "" and not fs.exists(dir) then
    fs.makeDir(dir)
  end

  local handle, err = fs.open(path, "w")
  if not handle then error("Could not write " .. path .. ": " .. tostring(err)) end

  handle.write(content)
  handle.close()
end

local function backupPath(path)
  if not fs.exists(path) then return nil end

  local backup = path .. ".backup_" .. tostring(os.getComputerID()) .. "_" .. tostring(math.floor(os.clock() * 1000))
  fs.move(path, backup)
  return backup
end

local function getInstallerRoot()
  local running = nil

  if shell and shell.getRunningProgram then
    running = shell.getRunningProgram()
    if shell.resolve then running = shell.resolve(running) end
  end

  if running then
    local dir = fs.getDir(running)
    if dir and dir ~= "" and fs.exists(fs.combine(dir, "sgnet")) then
      return dir
    end
  end

  if fs.exists("/disk/sgnet") then return "/disk" end
  if fs.exists("disk/sgnet") then return "disk" end

  error("Could not find installer disk root.")
end

local function makeStartup()
  return table.concat({
    "-- /startup.lua",
    "-- SGNet launcher",
    "",
    "local CONFIG_PATH = \"/sgnet/config.lua\"",
    "",
    "term.clear()",
    "term.setCursorPos(1, 1)",
    "",
    "print(\"SGNet startup\")",
    "print(\"-------------\")",
    "",
    "if not fs.exists(CONFIG_PATH) then",
    "  print(\"Missing config file: \" .. CONFIG_PATH)",
    "  return",
    "end",
    "",
    "local ok, config = pcall(dofile, CONFIG_PATH)",
    "if not ok then",
    "  print(\"Failed to load config:\")",
    "  print(config)",
    "  return",
    "end",
    "",
    "if type(config) ~= \"table\" then",
    "  print(\"Config did not return a table.\")",
    "  return",
    "end",
    "",
    "if config.role == \"controller\" then",
    "  shell.run(\"/sgnet/controller/network_controller.lua\")",
    "elseif config.role == \"gateway\" then",
    "  shell.run(\"/sgnet/gateway/base_gateway.lua\")",
    "else",
    "  print(\"Invalid SGNet role: \" .. tostring(config.role))",
    "end",
    ""
  }, "\n")
end

local function quote(value)
  return string.format("%q", tostring(value or ""))
end

local function makeConfig(options)
  local controllerValue = "nil"
  if options.controller_id ~= nil then
    controllerValue = tostring(options.controller_id)
  end

  return table.concat({
    "-- /sgnet/config.lua",
    "-- Generated by SGNet installer",
    "",
    "local config = {",
    "  network_name = " .. quote(options.network_name) .. ",",
    "  role = " .. quote(options.role) .. ",",
    "  node_id = " .. quote(options.node_id) .. ",",
    "  base_id = " .. quote(options.base_id) .. ",",
    "  dimension = " .. quote(options.dimension) .. ",",
    "  controller_id = " .. controllerValue .. ",",
    "  heartbeat_interval = " .. tostring(options.heartbeat_interval) .. ",",
    "  offline_after = " .. tostring(options.offline_after) .. ",",
    "  monitor = {",
    "    enabled = " .. tostring(options.monitor_enabled) .. ",",
    "    text_scale = " .. tostring(options.monitor_text_scale),
    "  },",
    "  log_dir = \"/sgnet/logs\",",
    "  protocols = {",
    "    discovery = \"sgnet.discovery\",",
    "    heartbeat = \"sgnet.heartbeat\",",
    "    status = \"sgnet.status\",",
    "    command = \"sgnet.command\",",
    "    response = \"sgnet.response\",",
    "    alert = \"sgnet.alert\"",
    "  }",
    "}",
    "",
    "return config",
    ""
  }, "\n")
end

local function defaultNodeId(role)
  local label = os.getComputerLabel()
  if label and label ~= "" then
    return string.gsub(string.lower(label), "%s+", "_")
  end

  if role == "controller" then return "main_controller" end

  return "gateway_" .. tostring(os.getComputerID())
end

clear()
print("SGNet Unified Installer")
print("======================")
print("")
print("Computer ID: " .. tostring(os.getComputerID()))
print("")

local root = getInstallerRoot()

local required = {
  "sgnet/lib/network.lua",
  "sgnet/lib/adapter_manager.lua",
  "sgnet/controller/network_controller.lua",
  "sgnet/gateway/base_gateway.lua",
  "sgnet/adapters/system.lua",
  "sgnet/adapters/peripheral_scan.lua",
  "sgnet/adapters/ae2_bridge.lua",
  "sgnet/tools/peripheral_report.lua",
  "sgnet/tools/ae2_test.lua"
}

for _, path in ipairs(required) do
  if not fs.exists(fs.combine(root, path)) then
    print("Installer disk is missing " .. path)
    return
  end
end

local role = askRole()

local options = {
  network_name = askString("Network name", "sgnet"),
  role = role,
  node_id = askString("Node ID", defaultNodeId(role)),
  base_id = askString("Base ID", role == "controller" and "control_room" or "overworld_main"),
  dimension = askString("Dimension", "overworld"),
  controller_id = nil,
  heartbeat_interval = askNumber("Heartbeat interval seconds", 5, false),
  offline_after = askNumber("Offline timeout seconds", 20, false),
  monitor_enabled = false,
  monitor_text_scale = 0.5
}

if role == "controller" then
  options.monitor_enabled = askYesNo("Use monitor if attached", true)
  options.monitor_text_scale = askNumber("Monitor text scale", 0.5, false)
else
  options.controller_id = askNumber("Controller computer ID", nil, true)
end

print("")
print("Install summary")
print("---------------")
print("Role: " .. options.role)
print("Node ID: " .. options.node_id)
print("Base ID: " .. options.base_id)
print("Dimension: " .. options.dimension)
print("Network: " .. options.network_name)

if options.controller_id then
  print("Controller ID: " .. tostring(options.controller_id))
else
  print("Controller ID: auto-discovery")
end

print("")
if not askYesNo("Install SGNet on this computer", true) then
  print("Install cancelled.")
  return
end

if fs.exists("/sgnet") then
  print("")
  if askYesNo("/sgnet exists. Back up and replace", true) then
    local backup = backupPath("/sgnet")
    print("Backed up to " .. tostring(backup))
  else
    print("Install cancelled.")
    return
  end
end

if fs.exists("/startup.lua") then
  print("")
  if askYesNo("/startup.lua exists. Back up and replace", true) then
    local backup = backupPath("/startup.lua")
    print("Backed up to " .. tostring(backup))
  else
    print("Install cancelled.")
    return
  end
end

print("")
print("Copying SGNet files...")
fs.copy(fs.combine(root, "sgnet"), "/sgnet")

if not fs.exists("/sgnet/logs") then fs.makeDir("/sgnet/logs") end

print("Writing config...")
writeFile("/sgnet/config.lua", makeConfig(options))

print("Writing startup...")
writeFile("/startup.lua", makeStartup())

print("")
print("SGNet installed successfully.")
print("")
print("Run this to start:")
print("startup")
print("")

if askYesNo("Reboot now", false) then os.reboot() end
]=====]

local NETWORK_LUA = [=====[
-- /sgnet/lib/network.lua
-- Shared SGNet network helpers

local M = {}

M.VERSION = 2

function M.nowMs()
  if os.epoch then return os.epoch("utc") end
  return math.floor(os.clock() * 1000)
end

function M.secondsSince(ms)
  if not ms then return 0 end
  return math.floor((M.nowMs() - ms) / 1000)
end

function M.ensureDir(path)
  if path and path ~= "" and not fs.exists(path) then fs.makeDir(path) end
end

function M.hasPeripheralType(name, wantedType)
  if peripheral.hasType then
    local ok, result = pcall(peripheral.hasType, name, wantedType)
    if ok then return result end
  end

  local kind = peripheral.getType(name)
  if type(kind) == "table" then
    for _, value in ipairs(kind) do
      if value == wantedType then return true end
    end
    return false
  end

  return kind == wantedType
end

function M.typeString(name)
  local kind = peripheral.getType(name)
  if type(kind) == "table" then return table.concat(kind, ",") end
  return tostring(kind or "unknown")
end

function M.findModem()
  local fallback = nil

  for _, name in ipairs(peripheral.getNames()) do
    if M.hasPeripheralType(name, "modem") then
      fallback = fallback or name
      local modem = peripheral.wrap(name)
      if modem and modem.isWireless and modem.isWireless() then
        return name, true
      end
    end
  end

  if fallback then return fallback, false end
  return nil, false
end

function M.openRednet()
  local modemName, isWireless = M.findModem()
  if not modemName then return false, nil, "No modem peripheral found." end

  if not rednet.isOpen(modemName) then rednet.open(modemName) end
  if not rednet.isOpen(modemName) then
    return false, modemName, "Found modem, but rednet failed to open it."
  end

  local modemKind = isWireless and "wireless_or_ender" or "wired"
  return true, modemName, modemKind
end

function M.getComputerLabelSafe()
  local label = os.getComputerLabel()
  if label == nil or label == "" then return "unlabeled" end
  return label
end

function M.message(config, messageType, data)
  return {
    sgnet = true,
    version = M.VERSION,
    network = config.network_name or "sgnet",
    type = messageType,
    from = config.node_id or ("computer_" .. tostring(os.getComputerID())),
    computer_id = os.getComputerID(),
    label = M.getComputerLabelSafe(),
    role = config.role or "unknown",
    base = config.base_id or "unknown",
    dimension = config.dimension or "unknown",
    time = M.nowMs(),
    data = data or {}
  }
end

function M.isValid(config, message)
  if type(message) ~= "table" then return false end
  if message.sgnet ~= true then return false end
  if message.version ~= M.VERSION then return false end
  if message.network ~= (config.network_name or "sgnet") then return false end
  if type(message.type) ~= "string" then return false end
  return true
end

function M.send(config, targetId, protocol, messageType, data)
  local message = M.message(config, messageType, data)
  return rednet.send(targetId, message, protocol)
end

function M.broadcast(config, protocol, messageType, data)
  local message = M.message(config, messageType, data)
  return rednet.broadcast(message, protocol)
end

function M.log(config, line)
  local logDir = config.log_dir or "/sgnet/logs"
  M.ensureDir(logDir)

  local nodeId = config.node_id or ("computer_" .. tostring(os.getComputerID()))
  local path = fs.combine(logDir, nodeId .. ".log")

  local handle = fs.open(path, "a")
  if not handle then return false end

  handle.writeLine("[" .. tostring(M.nowMs()) .. "] " .. tostring(line))
  handle.close()
  return true
end

function M.padRight(value, length)
  local text = tostring(value or "")
  if #text >= length then return string.sub(text, 1, length) end
  return text .. string.rep(" ", length - #text)
end

function M.trimTo(value, length)
  local text = tostring(value or "")
  if #text <= length then return text end
  return string.sub(text, 1, math.max(1, length - 3)) .. "..."
end

function M.safeCall(object, methodName, ...)
  if not object or type(object[methodName]) ~= "function" then
    return false, nil
  end

  local args = { ... }
  local ok, result = pcall(function()
    return object[methodName](table.unpack(args))
  end)

  if ok then return true, result end
  return false, result
end

return M
]=====]

local ADAPTER_MANAGER_LUA = [=====[
-- /sgnet/lib/adapter_manager.lua
-- Loads and runs SGNet adapters

local M = {}

local function basename(path)
  local name = fs.getName(path)
  return (string.gsub(name, "%.lua$", ""))
end

local function sortedLuaFiles(dir)
  local files = {}

  if not fs.exists(dir) then return files end

  for _, name in ipairs(fs.list(dir)) do
    local path = fs.combine(dir, name)
    if not fs.isDir(path) and string.sub(name, -4) == ".lua" then
      table.insert(files, path)
    end
  end

  table.sort(files)
  return files
end

function M.create(config, network)
  local manager = {
    config = config,
    network = network,
    adapters = {},
    errors = {},
    loaded_at = nil
  }

  function manager:addError(message)
    table.insert(self.errors, tostring(message))
    if self.network and self.network.log then
      self.network.log(self.config, "ADAPTER_ERROR " .. tostring(message))
    end
  end

  function manager:load()
    self.adapters = {}
    self.errors = {}
    self.loaded_at = os.clock()

    local dir = "/sgnet/adapters"
    local files = sortedLuaFiles(dir)

    for _, path in ipairs(files) do
      local ok, adapter = pcall(dofile, path)

      if not ok then
        self:addError(path .. ": load failed: " .. tostring(adapter))
      elseif type(adapter) ~= "table" then
        self:addError(path .. ": adapter did not return a table")
      else
        local id = adapter.id or basename(path)
        adapter.id = id
        adapter.path = path

        if type(adapter.init) == "function" then
          local initOk, initErr = pcall(adapter.init, self.config, self.network)
          if not initOk then
            adapter.init_error = tostring(initErr)
            self:addError(id .. ": init failed: " .. tostring(initErr))
          end
        end

        self.adapters[id] = adapter
      end
    end

    return true
  end

  function manager:list()
    local list = {}

    for id, adapter in pairs(self.adapters) do
      table.insert(list, {
        id = id,
        name = adapter.name or id,
        path = adapter.path,
        init_error = adapter.init_error
      })
    end

    table.sort(list, function(a, b) return tostring(a.id) < tostring(b.id) end)
    return list
  end

  function manager:status()
    local list = {}

    for id, adapter in pairs(self.adapters) do
      local entry = {
        id = id,
        name = adapter.name or id,
        online = false,
        message = "",
        data = {}
      }

      if adapter.init_error then
        entry.message = "init_error: " .. tostring(adapter.init_error)
      elseif type(adapter.status) == "function" then
        local ok, result = pcall(adapter.status)
        if ok and type(result) == "table" then
          for key, value in pairs(result) do entry[key] = value end
          if entry.online == nil then entry.online = true end
        elseif ok then
          entry.online = true
          entry.message = tostring(result or "ok")
        else
          entry.message = "status_error: " .. tostring(result)
        end
      else
        entry.online = true
        entry.message = "loaded"
      end

      table.insert(list, entry)
    end

    table.sort(list, function(a, b) return tostring(a.id) < tostring(b.id) end)

    return {
      count = #list,
      adapters = list,
      errors = self.errors,
      loaded_at = self.loaded_at
    }
  end

  function manager:call(adapterId, commandName, args)
    local adapter = self.adapters[adapterId]
    if not adapter then
      return false, "Adapter not loaded: " .. tostring(adapterId)
    end

    local fn = nil

    if type(adapter.commands) == "table" then
      fn = adapter.commands[commandName]
    end

    if type(fn) ~= "function" and type(adapter[commandName]) == "function" then
      fn = adapter[commandName]
    end

    if type(fn) ~= "function" then
      return false, "Unsupported adapter command: " .. tostring(adapterId) .. "." .. tostring(commandName)
    end

    local ok, result = pcall(fn, args or {})
    if not ok then return false, tostring(result) end

    return true, result
  end

  manager:load()
  return manager
end

return M
]=====]

local SYSTEM_ADAPTER_LUA = [=====[
-- /sgnet/adapters/system.lua

local adapter = {
  id = "system",
  name = "System"
}

function adapter.status()
  local data = {
    online = true,
    message = "online",
    data = {
      computer_id = os.getComputerID(),
      label = os.getComputerLabel() or "unlabeled",
      uptime = math.floor(os.clock()),
      free_space = fs.getFreeSpace and fs.getFreeSpace("/") or nil
    }
  }

  if turtle then
    data.data.turtle = true
    data.data.fuel_level = turtle.getFuelLevel()
    data.data.fuel_limit = turtle.getFuelLimit()
  end

  return data
end

adapter.commands = {}

function adapter.commands.get_status()
  return adapter.status()
end

return adapter
]=====]

local PERIPHERAL_SCAN_ADAPTER_LUA = [=====[
-- /sgnet/adapters/peripheral_scan.lua

local adapter = {
  id = "peripheral_scan",
  name = "Peripheral Scan"
}

local function scan()
  local list = {}

  for _, name in ipairs(peripheral.getNames()) do
    local methods = {}

    if peripheral.getMethods then
      local ok, result = pcall(peripheral.getMethods, name)
      if ok and type(result) == "table" then methods = result end
    end

    table.sort(methods)

    table.insert(list, {
      name = name,
      type = peripheral.getType(name),
      methods = methods
    })
  end

  table.sort(list, function(a, b) return tostring(a.name) < tostring(b.name) end)
  return list
end

function adapter.status()
  local list = scan()

  return {
    online = true,
    message = tostring(#list) .. " peripherals",
    data = {
      count = #list,
      peripherals = list
    }
  }
end

adapter.commands = {}

function adapter.commands.scan()
  return adapter.status()
end

return adapter
]=====]

local AE2_BRIDGE_ADAPTER_LUA = [=====[
-- /sgnet/adapters/ae2_bridge.lua
-- Advanced Peripherals ME Bridge adapter
-- Detection intentionally checks for known ME Bridge methods instead of strict peripheral type.

local adapter = {
  id = "ae2_bridge",
  name = "AE2 ME Bridge"
}

local bridgeName = nil
local bridge = nil

local DETECTION_METHODS = {
  "getItems",
  "isOnline",
  "getStoredEnergy",
  "getUsedItemStorage",
  "getAvailableItemStorage"
}

local function typeToString(value)
  if type(value) == "table" then return table.concat(value, ",") end
  return tostring(value or "")
end

local function hasMethod(object, methodName)
  return object and type(object[methodName]) == "function"
end

local function countKnownMethods(object)
  local count = 0
  local found = {}

  for _, methodName in ipairs(DETECTION_METHODS) do
    if hasMethod(object, methodName) then
      count = count + 1
      table.insert(found, methodName)
    end
  end

  return count, found
end

local function looksLikeMEBridge(name)
  local wrapped = peripheral.wrap(name)
  if not wrapped then return false, {} end

  local methodCount, found = countKnownMethods(wrapped)
  if methodCount > 0 then return true, found end

  local kind = string.lower(typeToString(peripheral.getType(name)))
  if string.find(kind, "mebridge", 1, true) or string.find(kind, "me_bridge", 1, true) then
    return true, found
  end

  return false, found
end

local function findBridge()
  for _, name in ipairs(peripheral.getNames()) do
    local ok = looksLikeMEBridge(name)
    if ok then
      bridgeName = name
      bridge = peripheral.wrap(name)
      return bridgeName, bridge
    end
  end

  bridgeName = nil
  bridge = nil
  return nil, nil
end

local function ensureBridge()
  if bridgeName and peripheral.isPresent and peripheral.isPresent(bridgeName) then
    bridge = peripheral.wrap(bridgeName)
    if bridge then return true end
  end

  local name = findBridge()
  return name ~= nil
end

local function safeCall(methodName, ...)
  if not ensureBridge() then return false, "ME Bridge not found" end
  if not hasMethod(bridge, methodName) then return false, "Method not available: " .. tostring(methodName) end

  local args = { ... }
  local ok, result = pcall(function()
    return bridge[methodName](table.unpack(args))
  end)

  if ok then return true, result end
  return false, tostring(result)
end

local function getItems()
  local ok, result = safeCall("getItems")
  if ok and type(result) == "table" then return true, result end

  ok, result = safeCall("getItems", {})
  if ok and type(result) == "table" then return true, result end

  return false, result or "getItems failed or did not return a table"
end

local function itemCount(item)
  if type(item) ~= "table" then return 0 end
  return tonumber(item.amount or item.count or item.size or item.qty or 0) or 0
end

local function itemName(item)
  if type(item) ~= "table" then return tostring(item) end
  return tostring(item.displayName or item.display_name or item.name or item.id or item.fingerprint or "unknown")
end

local function itemTechnicalName(item)
  if type(item) ~= "table" then return tostring(item) end
  return tostring(item.name or item.id or item.fingerprint or item.displayName or "unknown")
end

local function normalizedItem(item)
  return {
    display_name = itemName(item),
    name = itemTechnicalName(item),
    count = itemCount(item)
  }
end

local function sortedItems()
  local ok, items = getItems()
  if not ok then return false, items end

  local normalized = {}
  for _, item in pairs(items) do
    table.insert(normalized, normalizedItem(item))
  end

  table.sort(normalized, function(a, b)
    if a.count == b.count then return tostring(a.display_name) < tostring(b.display_name) end
    return a.count > b.count
  end)

  return true, normalized
end

function adapter.init()
  findBridge()
end

function adapter.status()
  local found = ensureBridge()

  if not found then
    return {
      online = false,
      message = "ME Bridge not found",
      data = {}
    }
  end

  local data = {
    side = bridgeName,
    type = typeToString(peripheral.getType(bridgeName))
  }

  local okOnline, isOnline = safeCall("isOnline")
  if okOnline then data.me_online = isOnline end

  local okEnergy, energy = safeCall("getStoredEnergy")
  if okEnergy then data.stored_energy = energy end

  local okMaxEnergy, maxEnergy = safeCall("getMaxStoredEnergy")
  if okMaxEnergy then data.max_stored_energy = maxEnergy end

  local okUsedItems, usedItems = safeCall("getUsedItemStorage")
  if okUsedItems then data.used_item_storage = usedItems end

  local okAvailableItems, availableItems = safeCall("getAvailableItemStorage")
  if okAvailableItems then data.available_item_storage = availableItems end

  return {
    online = okOnline and isOnline ~= false or true,
    message = "ME Bridge found on " .. tostring(bridgeName),
    data = data
  }
end

adapter.commands = {}

function adapter.commands.top_items(args)
  args = args or {}
  local limit = tonumber(args.limit or 10) or 10

  local ok, items = sortedItems()
  if not ok then return { ok = false, message = tostring(items), items = {} } end

  local output = {}
  for i = 1, math.min(limit, #items) do
    table.insert(output, items[i])
  end

  return {
    ok = true,
    message = "Top " .. tostring(#output) .. " stored items",
    items = output
  }
end

function adapter.commands.find_item(args)
  args = args or {}

  local query = string.lower(tostring(args.query or ""))
  local limit = tonumber(args.limit or 20) or 20

  if query == "" then
    return { ok = false, message = "Missing search query", items = {} }
  end

  local ok, items = sortedItems()
  if not ok then return { ok = false, message = tostring(items), items = {} } end

  local output = {}
  for _, item in ipairs(items) do
    local haystack = string.lower(tostring(item.display_name) .. " " .. tostring(item.name))
    if string.find(haystack, query, 1, true) then
      table.insert(output, item)
      if #output >= limit then break end
    end
  end

  return {
    ok = true,
    message = "Found " .. tostring(#output) .. " matching items for " .. tostring(args.query),
    query = args.query,
    items = output
  }
end

return adapter
]=====]

local CONTROLLER_LUA = [=====[
-- /sgnet/controller/network_controller.lua
-- SGNet central controller

local CONFIG_PATH = "/sgnet/config.lua"
local NETWORK_PATH = "/sgnet/lib/network.lua"

local okConfig, config = pcall(dofile, CONFIG_PATH)
if not okConfig then error("Failed to load config: " .. tostring(config)) end

local okNetwork, network = pcall(dofile, NETWORK_PATH)
if not okNetwork then error("Failed to load network library: " .. tostring(network)) end

local opened, modemName, modemKindOrError = network.openRednet()
if not opened then error(modemKindOrError or "Could not open rednet.") end

local modemKind = modemKindOrError

pcall(rednet.host, config.protocols.discovery, config.node_id)
pcall(rednet.host, config.protocols.status, config.node_id)
pcall(rednet.host, config.protocols.response, config.node_id)

local nodes = {}
local alerts = {}
local detailLines = {}
local selectedIndex = 1
local lastAnnounce = 0
local running = true

local function addAlert(message)
  local line = tostring(message)
  table.insert(alerts, 1, line)
  while #alerts > 6 do table.remove(alerts) end
  network.log(config, "ALERT " .. line)
end

local function setDetails(lines)
  detailLines = lines or {}
  while #detailLines > 10 do table.remove(detailLines) end
end

local function getScreen()
  if config.monitor and config.monitor.enabled then
    local monitor = peripheral.find("monitor")
    if monitor then
      if config.monitor.text_scale then pcall(monitor.setTextScale, config.monitor.text_scale) end
      return monitor
    end
  end

  return term.current()
end

local screen = getScreen()

local function canUseColor()
  return screen.isColor and screen.isColor() and colors
end

local function setColor(color)
  if canUseColor() and color then pcall(screen.setTextColor, color) end
end

local function resetColor()
  if canUseColor() then pcall(screen.setTextColor, colors.white) end
end

local function writeAt(x, y, text, color)
  local width = screen.getSize()
  local output = network.trimTo(text, math.max(1, width - x + 1))

  if color then setColor(color) else resetColor() end
  screen.setCursorPos(x, y)
  screen.write(output)
  resetColor()
end

local function countNodes()
  local count = 0
  for _ in pairs(nodes) do count = count + 1 end
  return count
end

local function sortedNodes()
  local list = {}

  for _, node in pairs(nodes) do table.insert(list, node) end

  table.sort(list, function(a, b)
    return tostring(a.node_id) < tostring(b.node_id)
  end)

  if selectedIndex < 1 then selectedIndex = 1 end
  if selectedIndex > #list then selectedIndex = #list end
  if #list == 0 then selectedIndex = 1 end

  return list
end

local function selectedNode()
  local list = sortedNodes()
  return list[selectedIndex], list
end

local function updateOfflineAlerts()
  local offlineAfter = config.offline_after or 20

  for _, node in pairs(nodes) do
    local age = network.secondsSince(node.last_seen)
    local isOffline = age > offlineAfter

    if isOffline and not node.offline_alerted then
      node.offline_alerted = true
      addAlert(node.node_id .. " is offline.")
    elseif not isOffline then
      node.offline_alerted = false
    end
  end
end

local function adapterSummary(node)
  if not node.adapters then return "" end

  local parts = {}
  for _, adapter in ipairs(node.adapters) do
    local status = adapter.online and "on" or "off"
    table.insert(parts, tostring(adapter.id) .. ":" .. status)
  end

  return table.concat(parts, " ")
end

local function draw()
  screen.clear()
  screen.setCursorPos(1, 1)

  local width, height = screen.getSize()
  local list = sortedNodes()

  writeAt(1, 1, "SGNet Controller", colors and colors.cyan or nil)
  writeAt(1, 2, "Computer ID: " .. tostring(os.getComputerID()))
  writeAt(1, 3, "Node: " .. tostring(config.node_id))
  writeAt(1, 4, "Modem: " .. tostring(modemName) .. " (" .. tostring(modemKind) .. ")")
  writeAt(1, 5, "Network: " .. tostring(config.network_name) .. " | Known gateways: " .. tostring(countNodes()))

  local y = 7
  writeAt(1, y, "   Status   ID    Node                         Base                 Dim        Seen")
  y = y + 1
  writeAt(1, y, string.rep("-", math.min(width, 90)))
  y = y + 1

  if #list == 0 then
    writeAt(1, y, "No gateways have checked in yet.")
    y = y + 2
  else
    for index, node in ipairs(list) do
      if y >= height - 11 then
        writeAt(1, y, "...more nodes not shown...")
        break
      end

      local age = network.secondsSince(node.last_seen)
      local isOffline = age > (config.offline_after or 20)
      local status = isOffline and "OFFLINE" or "ONLINE"
      local color = nil
      if colors then color = isOffline and colors.red or colors.lime end

      local marker = index == selectedIndex and ">" or " "
      local line =
        marker .. "  " ..
        network.padRight(status, 9) ..
        network.padRight(node.computer_id, 6) ..
        network.padRight(network.trimTo(node.node_id, 28), 29) ..
        network.padRight(network.trimTo(node.base, 20), 21) ..
        network.padRight(network.trimTo(node.dimension, 10), 11) ..
        tostring(age) .. "s"

      writeAt(1, y, line, color)
      y = y + 1

      if index == selectedIndex and node.adapters then
        writeAt(4, y, "Adapters: " .. adapterSummary(node), colors and colors.lightBlue or nil)
        y = y + 1
      end
    end
  end

  y = math.max(y + 1, height - 8)
  writeAt(1, y, "Keys: Up/Down Select | P Ping | I Identify | S Status | A Adapters | R Reload | T AE2 Top | F Find | Q Quit", colors and colors.yellow or nil)
  y = y + 1

  if #detailLines > 0 then
    for i = 1, math.min(#detailLines, 5) do
      if y >= height then break end
      writeAt(1, y, detailLines[i])
      y = y + 1
    end
  else
    writeAt(1, y, "Alerts:")
    y = y + 1

    if #alerts == 0 then
      writeAt(1, y, "No alerts.")
    else
      for i = 1, math.min(#alerts, 5) do
        if y >= height then break end
        writeAt(1, y, "- " .. alerts[i], colors and colors.orange or nil)
        y = y + 1
      end
    end
  end
end

local function announceController()
  network.broadcast(config, config.protocols.discovery, "controller_announce", {
    controller_id = os.getComputerID(),
    controller_node = config.node_id,
    status = "online",
    modem = modemName,
    modem_kind = modemKind
  })
end

local function updateNode(senderId, message, protocol)
  if senderId == os.getComputerID() then return end

  local data = message.data or {}
  local key = tostring(senderId)
  local node = nodes[key] or {}

  node.computer_id = senderId
  node.node_id = message.from or ("computer_" .. tostring(senderId))
  node.label = message.label or "unlabeled"
  node.role = message.role or "unknown"
  node.base = message.base or "unknown"
  node.dimension = message.dimension or "unknown"
  node.last_seen = network.nowMs()
  node.last_type = message.type
  node.last_protocol = protocol
  node.status = data.status or "online"
  node.modem = data.modem
  node.modem_kind = data.modem_kind
  node.uptime = data.uptime

  if data.adapters then node.adapters = data.adapters end
  if data.adapter_errors then node.adapter_errors = data.adapter_errors end

  nodes[key] = node

  if message.type == "gateway_discover" then
    network.send(config, senderId, config.protocols.discovery, "controller_announce", {
      controller_id = os.getComputerID(),
      controller_node = config.node_id,
      status = "online",
      modem = modemName,
      modem_kind = modemKind
    })

    addAlert("Discovered gateway: " .. tostring(node.node_id))
  end
end

local function formatItemLine(index, item)
  return tostring(index) .. ". " .. tostring(item.count or "?") .. "x " .. tostring(item.display_name or item.name or "unknown")
end

local function handleResponse(senderId, message)
  local data = message.data or {}
  local command = data.command or "unknown"
  local node = nodes[tostring(senderId)]
  local nodeName = node and node.node_id or tostring(senderId)

  if data.ok then
    addAlert(nodeName .. " " .. command .. ": " .. tostring(data.message or "ok"))
  else
    addAlert(nodeName .. " " .. command .. " failed: " .. tostring(data.message or "error"))
  end

  local result = data.result
  if type(result) == "table" and type(result.items) == "table" then
    local lines = {}
    table.insert(lines, nodeName .. " " .. command .. ": " .. tostring(result.message or data.message or "results"))

    if #result.items == 0 then
      table.insert(lines, "No items returned.")
    else
      for i, item in ipairs(result.items) do
        table.insert(lines, formatItemLine(i, item))
        if i >= 9 then break end
      end
    end

    setDetails(lines)
  elseif type(result) == "table" and type(result.adapters) == "table" then
    local lines = {}
    table.insert(lines, nodeName .. " adapters:")

    for _, adapter in ipairs(result.adapters) do
      local state = adapter.online and "ONLINE" or "OFFLINE"
      table.insert(lines, "- " .. tostring(adapter.id) .. " = " .. state .. " | " .. tostring(adapter.message or ""))
    end

    if result.errors and #result.errors > 0 then
      table.insert(lines, "Errors: " .. table.concat(result.errors, " | "))
    end

    setDetails(lines)
  elseif data.message then
    setDetails({ nodeName .. " " .. command .. ": " .. tostring(data.message) })
  end
end

local function networkLoop()
  announceController()
  lastAnnounce = network.nowMs()

  while running do
    local now = network.nowMs()
    if now - lastAnnounce > 10000 then
      announceController()
      lastAnnounce = now
    end

    local senderId, message, protocol = rednet.receive(nil, 0.5)
    if senderId and network.isValid(config, message) then
      if message.type == "command_response" then
        handleResponse(senderId, message)
      else
        updateNode(senderId, message, protocol)
      end
    end
  end
end

local function drawLoop()
  while running do
    updateOfflineAlerts()
    draw()
    os.sleep(1)
  end
end

local function sendCommand(command, args)
  local node = selectedNode()
  if not node then
    addAlert("No gateway selected.")
    return
  end

  network.send(config, node.computer_id, config.protocols.command, "command", {
    command = command,
    args = args or {}
  })

  addAlert("Sent " .. command .. " to " .. tostring(node.node_id))
end

local function promptOnTerminal(prompt)
  local old = term.redirect(term.native and term.native() or term.current())

  term.clear()
  term.setCursorPos(1, 1)
  print("SGNet Controller Input")
  print("----------------------")
  write(prompt)

  local value = read()

  if old then term.redirect(old) end

  return value
end

local function keyLoop()
  while running do
    local _, key = os.pullEvent("key")

    local list = sortedNodes()

    if key == keys.up then
      selectedIndex = math.max(1, selectedIndex - 1)
    elseif key == keys.down then
      selectedIndex = math.min(math.max(#list, 1), selectedIndex + 1)
    elseif key == keys.p then
      sendCommand("ping")
    elseif key == keys.i then
      sendCommand("identify")
    elseif key == keys.s then
      sendCommand("status")
    elseif key == keys.a then
      sendCommand("adapter_status")
    elseif key == keys.r then
      sendCommand("reload_adapters")
    elseif key == keys.t then
      sendCommand("ae2_top", { limit = 10 })
    elseif key == keys.f then
      local query = promptOnTerminal("Find AE2 item: ")
      if query and query ~= "" then
        sendCommand("ae2_find", { query = query, limit = 20 })
      else
        addAlert("AE2 find cancelled.")
      end
    elseif key == keys.q then
      running = false
      term.clear()
      term.setCursorPos(1, 1)
      print("SGNet controller stopped.")
      return
    end
  end
end

network.log(config, "Controller started on modem " .. tostring(modemName))
parallel.waitForAny(networkLoop, drawLoop, keyLoop)
]=====]

local GATEWAY_LUA = [=====[
-- /sgnet/gateway/base_gateway.lua
-- SGNet base gateway

local CONFIG_PATH = "/sgnet/config.lua"
local NETWORK_PATH = "/sgnet/lib/network.lua"
local ADAPTER_MANAGER_PATH = "/sgnet/lib/adapter_manager.lua"

local okConfig, config = pcall(dofile, CONFIG_PATH)
if not okConfig then error("Failed to load config: " .. tostring(config)) end

local okNetwork, network = pcall(dofile, NETWORK_PATH)
if not okNetwork then error("Failed to load network library: " .. tostring(network)) end

local okAdapterManager, adapterManagerLib = pcall(dofile, ADAPTER_MANAGER_PATH)
if not okAdapterManager then error("Failed to load adapter manager: " .. tostring(adapterManagerLib)) end

local opened, modemName, modemKindOrError = network.openRednet()
if not opened then error(modemKindOrError or "Could not open rednet.") end

local modemKind = modemKindOrError
local manager = adapterManagerLib.create(config, network)

pcall(rednet.host, config.protocols.discovery, config.node_id)
pcall(rednet.host, config.protocols.status, config.node_id)

local controllerId = config.controller_id
local lastControllerSeen = nil
local lastStatusLine = "Starting..."
local alertLine = ""
local running = true

local function adapterHeartbeatSummary()
  local status = manager:status()
  local adapters = {}

  for _, entry in ipairs(status.adapters or {}) do
    table.insert(adapters, {
      id = entry.id,
      name = entry.name,
      online = entry.online,
      message = entry.message
    })
  end

  return adapters, status.errors or {}
end

local function draw()
  term.clear()
  term.setCursorPos(1, 1)

  print("SGNet Base Gateway")
  print("------------------")
  print("Computer ID: " .. tostring(os.getComputerID()))
  print("Node: " .. tostring(config.node_id))
  print("Base: " .. tostring(config.base_id))
  print("Dimension: " .. tostring(config.dimension))
  print("Network: " .. tostring(config.network_name))
  print("Modem: " .. tostring(modemName) .. " (" .. tostring(modemKind) .. ")")
  print("")

  if controllerId then
    local age = lastControllerSeen and network.secondsSince(lastControllerSeen) or "?"
    print("Controller: " .. tostring(controllerId) .. " | last seen " .. tostring(age) .. "s ago")
  else
    print("Controller: searching...")
  end

  print("")
  print("Status: " .. tostring(lastStatusLine))

  if alertLine ~= "" then print("Alert: " .. tostring(alertLine)) end

  print("")
  print("Adapters:")

  local status = manager:status()
  for _, entry in ipairs(status.adapters or {}) do
    local state = entry.online and "ONLINE" or "OFFLINE"
    print("- " .. tostring(entry.id) .. ": " .. state .. " | " .. tostring(entry.message or ""))
  end

  if status.errors and #status.errors > 0 then
    print("")
    print("Adapter errors:")
    for _, err in ipairs(status.errors) do print("- " .. tostring(err)) end
  end

  print("")
  print("Press Ctrl+T to terminate.")
end

local function discoverController()
  local adapters, adapterErrors = adapterHeartbeatSummary()

  network.broadcast(config, config.protocols.discovery, "gateway_discover", {
    status = "online",
    modem = modemName,
    modem_kind = modemKind,
    uptime = math.floor(os.clock()),
    adapters = adapters,
    adapter_errors = adapterErrors
  })

  lastStatusLine = "Broadcasting discovery..."
  network.log(config, "Broadcasting controller discovery.")
end

local function sendHeartbeat()
  local adapters, adapterErrors = adapterHeartbeatSummary()

  local data = {
    status = "online",
    modem = modemName,
    modem_kind = modemKind,
    uptime = math.floor(os.clock()),
    controller_id = controllerId,
    adapters = adapters,
    adapter_errors = adapterErrors
  }

  if controllerId then
    network.send(config, controllerId, config.protocols.heartbeat, "heartbeat", data)
    lastStatusLine = "Heartbeat sent to controller " .. tostring(controllerId)
  else
    discoverController()
  end
end

local function sendResponse(targetId, ok, command, message, result)
  network.send(config, targetId, config.protocols.response, "command_response", {
    ok = ok,
    command = command,
    message = message,
    result = result
  })
end

local function handleCommand(senderId, message)
  if controllerId and senderId ~= controllerId then
    network.log(config, "Rejected command from non-controller ID " .. tostring(senderId))
    return
  end

  local data = message.data or {}
  local command = data.command
  local args = data.args or {}

  if command == "ping" then
    sendResponse(senderId, true, command, "pong from " .. tostring(config.node_id))
  elseif command == "identify" then
    alertLine = "Identify command received."
    sendResponse(senderId, true, command, "identify acknowledged")
  elseif command == "status" then
    local status = {
      node_id = config.node_id,
      base_id = config.base_id,
      dimension = config.dimension,
      computer_id = os.getComputerID(),
      uptime = math.floor(os.clock()),
      modem = modemName,
      modem_kind = modemKind
    }
    sendResponse(senderId, true, command, "gateway status returned", status)
  elseif command == "adapter_status" then
    sendResponse(senderId, true, command, "adapter status returned", manager:status())
  elseif command == "reload_adapters" then
    manager:load()
    sendResponse(senderId, true, command, "adapters reloaded", manager:status())
  elseif command == "ae2_top" then
    local ok, result = manager:call("ae2_bridge", "top_items", args)
    sendResponse(senderId, ok, command, ok and (result.message or "AE2 top items returned") or tostring(result), result)
  elseif command == "ae2_find" then
    local ok, result = manager:call("ae2_bridge", "find_item", args)
    sendResponse(senderId, ok, command, ok and (result.message or "AE2 search returned") or tostring(result), result)
  else
    sendResponse(senderId, false, command or "unknown", "Unsupported command.")
  end
end

local function receiveLoop()
  while running do
    local senderId, message, protocol = rednet.receive(nil, 2)

    if senderId and network.isValid(config, message) then
      if message.type == "controller_announce" and message.role == "controller" then
        controllerId = senderId
        lastControllerSeen = network.nowMs()
        alertLine = ""
        lastStatusLine = "Controller found: " .. tostring(controllerId)
        network.log(config, "Controller found: " .. tostring(controllerId))
      elseif protocol == config.protocols.command and message.type == "command" then
        handleCommand(senderId, message)
      elseif senderId == controllerId then
        lastControllerSeen = network.nowMs()
      end
    end
  end
end

local function heartbeatLoop()
  discoverController()

  while running do
    if controllerId and lastControllerSeen then
      local age = network.secondsSince(lastControllerSeen)
      if age > (config.offline_after or 20) then
        alertLine = "Controller timed out. Rediscovering..."
        network.log(config, "Controller timed out. Rediscovering.")

        if not config.controller_id then
          controllerId = nil
          lastControllerSeen = nil
        end
      end
    end

    sendHeartbeat()
    os.sleep(config.heartbeat_interval or 5)
  end
end

local function drawLoop()
  while running do
    draw()
    os.sleep(1)
  end
end

network.log(config, "Gateway started on modem " .. tostring(modemName))
parallel.waitForAny(receiveLoop, heartbeatLoop, drawLoop)
]=====]

local PERIPHERAL_REPORT_LUA = [=====[
-- /sgnet/tools/peripheral_report.lua
-- Prints and saves a report of attached peripherals and methods.

local function typeToString(value)
  if type(value) == "table" then return table.concat(value, ",") end
  return tostring(value or "unknown")
end

local function getMethods(name)
  if not peripheral.getMethods then return {} end

  local ok, methods = pcall(peripheral.getMethods, name)
  if ok and type(methods) == "table" then
    table.sort(methods)
    return methods
  end

  return {}
end

local function ensureDir(path)
  if not fs.exists(path) then fs.makeDir(path) end
end

term.clear()
term.setCursorPos(1, 1)

print("SGNet Peripheral Report")
print("=======================")
print("Computer ID: " .. tostring(os.getComputerID()))
print("")

local names = peripheral.getNames()
table.sort(names)

local lines = {}
table.insert(lines, "SGNet Peripheral Report")
table.insert(lines, "Computer ID: " .. tostring(os.getComputerID()))
table.insert(lines, "")

if #names == 0 then
  print("No peripherals found.")
  table.insert(lines, "No peripherals found.")
else
  for _, name in ipairs(names) do
    local typeText = typeToString(peripheral.getType(name))
    local methods = getMethods(name)

    print("Peripheral: " .. name)
    print("Type: " .. typeText)
    print("Methods: " .. tostring(#methods))

    table.insert(lines, "Peripheral: " .. name)
    table.insert(lines, "Type: " .. typeText)
    table.insert(lines, "Methods:")

    for _, methodName in ipairs(methods) do
      print(" - " .. methodName)
      table.insert(lines, " - " .. methodName)
    end

    print("")
    table.insert(lines, "")
  end
end

ensureDir("/sgnet")
ensureDir("/sgnet/logs")

local path = "/sgnet/logs/peripheral_report_" .. tostring(os.getComputerID()) .. ".txt"
local handle = fs.open(path, "w")
if handle then
  handle.write(table.concat(lines, "\n"))
  handle.close()
  print("Saved report to " .. path)
else
  print("Could not save report.")
end
]=====]

local AE2_TEST_LUA = [=====[
-- /sgnet/tools/ae2_test.lua
-- Tests Advanced Peripherals ME Bridge detection and basic item reads.

local DETECTION_METHODS = {
  "getItems",
  "isOnline",
  "getStoredEnergy",
  "getUsedItemStorage",
  "getAvailableItemStorage"
}

local function typeToString(value)
  if type(value) == "table" then return table.concat(value, ",") end
  return tostring(value or "unknown")
end

local function hasMethod(object, methodName)
  return object and type(object[methodName]) == "function"
end

local function knownMethods(object)
  local found = {}

  for _, methodName in ipairs(DETECTION_METHODS) do
    if hasMethod(object, methodName) then
      table.insert(found, methodName)
    end
  end

  return found
end

local function looksLikeBridge(name)
  local wrapped = peripheral.wrap(name)
  if not wrapped then return false, {} end

  local found = knownMethods(wrapped)
  if #found > 0 then return true, found end

  local kind = string.lower(typeToString(peripheral.getType(name)))
  if string.find(kind, "mebridge", 1, true) or string.find(kind, "me_bridge", 1, true) then
    return true, found
  end

  return false, found
end

local function safeCall(object, methodName, ...)
  if not object or type(object[methodName]) ~= "function" then
    return false, "missing method: " .. tostring(methodName)
  end

  local args = { ... }
  local ok, result = pcall(function()
    return object[methodName](table.unpack(args))
  end)

  if ok then return true, result end
  return false, tostring(result)
end

local function getItems(bridge)
  local ok, result = safeCall(bridge, "getItems")
  if ok and type(result) == "table" then return true, result end

  ok, result = safeCall(bridge, "getItems", {})
  if ok and type(result) == "table" then return true, result end

  return false, result
end

local function itemCount(item)
  if type(item) ~= "table" then return 0 end
  return tonumber(item.amount or item.count or item.size or item.qty or 0) or 0
end

local function itemName(item)
  if type(item) ~= "table" then return tostring(item) end
  return tostring(item.displayName or item.display_name or item.name or item.id or item.fingerprint or "unknown")
end

term.clear()
term.setCursorPos(1, 1)

print("SGNet AE2 Bridge Test")
print("====================")
print("Computer ID: " .. tostring(os.getComputerID()))
print("")

local names = peripheral.getNames()
table.sort(names)

print("Peripherals:")
for _, name in ipairs(names) do
  local wrapped = peripheral.wrap(name)
  local found = knownMethods(wrapped)

  print("- " .. name .. " | " .. typeToString(peripheral.getType(name)) .. " | methods: " .. table.concat(found, ", "))
end

print("")

local bridgeName = nil
local bridge = nil

for _, name in ipairs(names) do
  local ok = looksLikeBridge(name)
  if ok then
    bridgeName = name
    bridge = peripheral.wrap(name)
    break
  end
end

if not bridge then
  print("No ME Bridge detected.")
  print("")
  print("Check:")
  print("- Advanced Peripherals is installed on both server and client/modpack.")
  print("- The ME Bridge block is touching this computer or connected by wired modem.")
  print("- Run: peripheral.getNames()")
  return
end

print("ME Bridge detected on: " .. tostring(bridgeName))
print("Type: " .. typeToString(peripheral.getType(bridgeName)))
print("")

local okOnline, isOnline = safeCall(bridge, "isOnline")
if okOnline then print("ME online: " .. tostring(isOnline)) end

local okEnergy, energy = safeCall(bridge, "getStoredEnergy")
if okEnergy then print("Stored energy: " .. tostring(energy)) end

local okUsed, used = safeCall(bridge, "getUsedItemStorage")
if okUsed then print("Used item storage: " .. tostring(used)) end

print("")
print("Reading items...")

local okItems, items = getItems(bridge)
if not okItems then
  print("Failed to read items: " .. tostring(items))
  return
end

local normalized = {}
for _, item in pairs(items) do
  table.insert(normalized, {
    name = itemName(item),
    count = itemCount(item)
  })
end

table.sort(normalized, function(a, b)
  if a.count == b.count then return tostring(a.name) < tostring(b.name) end
  return a.count > b.count
end)

print("Items returned: " .. tostring(#normalized))
print("Top items:")

for i = 1, math.min(10, #normalized) do
  print(tostring(i) .. ". " .. tostring(normalized[i].count) .. "x " .. tostring(normalized[i].name))
end
]=====]

local README = [=====[
SGNet Unified Installer Disk

Run this from a target computer:
/disk/install

Recommended install order:
1. Install controller first.
2. Start controller with: startup
3. Install one gateway.
4. Start gateway with: startup
5. Confirm gateway appears on controller.
6. Install remaining gateways.

Current controller hotkeys:
- Up / Down = select gateway
- P = ping selected gateway
- I = identify selected gateway
- S = request status
- A = request adapter status
- R = reload adapters
- T = AE2 top stored items
- F = AE2 find/search item
- Q = quit controller

Included adapters/tools:
- system
- peripheral_scan
- ae2_bridge
- /sgnet/tools/peripheral_report.lua
- /sgnet/tools/ae2_test.lua

Use ender modems for cross-dimensional SGNet.
Use wireless modems for local testing.
]=====]

local FILES = {
  ["install.lua"] = INSTALLER_LUA,
  ["README.txt"] = README,
  ["VERSION.txt"] = VERSION,
  ["sgnet/lib/network.lua"] = NETWORK_LUA,
  ["sgnet/lib/adapter_manager.lua"] = ADAPTER_MANAGER_LUA,
  ["sgnet/controller/network_controller.lua"] = CONTROLLER_LUA,
  ["sgnet/gateway/base_gateway.lua"] = GATEWAY_LUA,
  ["sgnet/adapters/system.lua"] = SYSTEM_ADAPTER_LUA,
  ["sgnet/adapters/peripheral_scan.lua"] = PERIPHERAL_SCAN_ADAPTER_LUA,
  ["sgnet/adapters/ae2_bridge.lua"] = AE2_BRIDGE_ADAPTER_LUA,
  ["sgnet/tools/peripheral_report.lua"] = PERIPHERAL_REPORT_LUA,
  ["sgnet/tools/ae2_test.lua"] = AE2_TEST_LUA
}

local function clear()
  term.clear()
  term.setCursorPos(1, 1)
end

local function askYesNo(prompt, default)
  while true do
    local suffix = default and " [Y/n]: " or " [y/N]: "
    write(prompt .. suffix)

    local answer = string.lower(read() or "")
    if answer == "" then
      return default
    elseif answer == "y" or answer == "yes" then
      return true
    elseif answer == "n" or answer == "no" then
      return false
    end

    print("Please answer y or n.")
  end
end

local function hasPeripheralType(name, wantedType)
  if peripheral.hasType then
    local ok, result = pcall(peripheral.hasType, name, wantedType)
    if ok then return result end
  end

  local kind = peripheral.getType(name)
  if type(kind) == "table" then
    for _, value in ipairs(kind) do
      if value == wantedType then return true end
    end
    return false
  end

  return kind == wantedType
end

local function findDrive()
  for _, name in ipairs(peripheral.getNames()) do
    if hasPeripheralType(name, "drive") then return name end
  end

  return nil
end

local function getDiskMount()
  local drive = findDrive()

  if not drive then return nil, nil, "No disk drive found." end
  if not disk.isPresent(drive) then return drive, nil, "Disk drive found, but no disk is inserted." end
  if not disk.hasData(drive) then return drive, nil, "Inserted disk does not provide writable data. Use a floppy disk." end

  local mount = disk.getMountPath(drive)
  if not mount then return drive, nil, "Could not get disk mount path." end
  if fs.isReadOnly(mount) then return drive, mount, "Disk is read-only." end

  return drive, mount, nil
end

local function writeFile(path, content)
  local dir = fs.getDir(path)
  if dir and dir ~= "" and not fs.exists(dir) then
    fs.makeDir(dir)
  end

  local handle, err = fs.open(path, "w")
  if not handle then error("Could not write " .. path .. ": " .. tostring(err)) end

  handle.write(content)
  handle.close()
end

local function clearDisk(mount)
  for _, item in ipairs(fs.list(mount)) do
    fs.delete(fs.combine(mount, item))
  end
end

clear()
print("SGNet Installer Disk Builder")
print("============================")
print("Version: " .. VERSION)
print("")

local drive, mount, err = getDiskMount()
if err then
  print(err)
  return
end

print("Disk drive: " .. tostring(drive))
print("Disk path: " .. tostring(mount))
print("")
print("This will erase the inserted floppy disk and create")
print("a reusable SGNet unified installer disk.")
print("")

if not askYesNo("Create installer disk", false) then
  print("Cancelled.")
  return
end

pcall(disk.setLabel, drive, "SGNet Installer")

print("")
print("Clearing disk...")
clearDisk(mount)

print("Writing installer files...")
local paths = {}

for path in pairs(FILES) do table.insert(paths, path) end
table.sort(paths)

for _, path in ipairs(paths) do
  writeFile(fs.combine(mount, path), FILES[path])
end

print("")
print("Installer disk created successfully.")
print("")
print("Disk contents:")
for _, path in ipairs(paths) do
  print("- " .. path)
end

print("")
print("To use it on another computer:")
print("/disk/install")
